---
title: "student-por cleaning"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(tidyverse)
student_por <- read_csv("https://raw.githubusercontent.com/kwonjhk/StudentAlcohol/master/Data/Raw/student-por.csv")
```

```{r}
any(is.na(student_por))
```
There are no explicitly missing values.

```{r}
#New variable creation
studalc = student_por %>%
  #Gedu = Medu if guardian == mother, Fedu if guardian == father, max(Medu, Fedu) otherwise/guardian == other
  mutate(Gedu = ifelse(guardian == "mother", Medu, 
                       ifelse(guardian == "father", Fedu, 
                       ifelse(Medu > Fedu, Medu, Fedu)))) %>%
  #Alc = 0 if Walc and Dalc == 1 (no drinking), 1 otherwise
  mutate(Alc = ifelse(Dalc == 1 & Walc == 1, 0, 1)) %>%
  #binary variable signifying improvement in grade from period 1 to period 2
  mutate(G4 = ifelse(G2 < G1, 0, 1)) %>%
  #Firstgen = 1 if student is an aspiring first-generation college student, 0 otherwise
  mutate(firstgen = 
           ifelse(Medu < 3 & Fedu < 3 & higher == "yes", 1, 0))
```



```{r}
#Variable reformatting
studalc = studalc %>%
  mutate(schoolsup = ifelse(schoolsup=="yes", 1, 0),
         #convert yes/no to 1/0
         famsup = ifelse(famsup=="yes", 1, 0),
         paid = ifelse(paid=="yes", 1, 0),
         activities = ifelse(activities=="yes", 1, 0),
         nursery = ifelse(nursery=="yes", 1, 0),
         higher = ifelse(higher=="yes", 1, 0),
         internet = ifelse(internet=="yes", 1, 0),
         romantic = ifelse(romantic=="yes", 1, 0),
         #change address levels to be more descriptive
         address = ifelse(address=="U", "Urban", "Rural"),
         #convert numbers to factor levels
         famrel = factor(famrel, 
                         levels=c(1,2,3,4,5), 
                         labels=c("Very Bad", "Bad", "Neutral", "Good", "Excellent")), 
         freetime = factor(freetime, 
                           levels=c(1,2,3,4,5), 
                           labels=c("Very Low", "Low", "Medium", "High", "Very High")),
         goout = factor(goout, 
                        levels=c(1,2,3,4,5),
                        labels=c("Very Low", "Low", "Medium", "High", "Very High")), 
         health = factor(health, 
                         levels=c(1,2,3,4,5), 
                         labels=c("Very Bad", "Bad", "Average", "Good", "Very Good"))
         ) %>%
  select(-Medu, -Fedu, -Dalc, -Walc)
```

Then, export the reformatted data into a .csv file:
```{r}
write_csv(studalc, "studalc-por.csv")
```
