---
title: "student-por cleaning"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(tidyverse)
```

```{r}
#change to the local file address of student-por.csv
student_por <- data.table::fread("~/Downloads/STOR320/Project/student-por.csv", stringsAsFactors=TRUE)
```

```{r}
any(is.na(student_por))
```
There are no explicitly missing values.

```{r}
student_por = student_por %>%
  mutate(schoolsup = ifelse(schoolsup=="yes", 1, 0),
         #convert yes/no to 1/0
         famsup = ifelse(famsup=="yes", 1, 0),
         paid = ifelse(paid=="yes", 1, 0),
         activities = ifelse(activities=="yes", 1, 0),
         nursery = ifelse(nursery=="yes", 1, 0),
         higher = ifelse(higher=="yes", 1, 0),
         internet = ifelse(internet=="yes", 1, 0),
         romantic = ifelse(romantic=="yes", 1, 0),
         #change address levels to be more descriptive
         address = ifelse(address=="U", "Urban", "Rural"),
         #change 1 = 10 hours to 1 = 1 hour
         studytime = 10*studytime, 
         #convert numbers to factor levels
         famrel = factor(famrel, 
                         levels=c(1,2,3,4,5), 
                         labels=c("Very Bad", "Bad", "Neutral", "Good", "Excellent")), 
         freetime = factor(freetime, 
                           levels=c(1,2,3,4,5), 
                           labels=c("Very Low", "Low", "Medium", "High", "Very High")),
         goout = factor(goout, 
                        levels=c(1,2,3,4,5), 
                        labels=c("Very Low", "Low", "Medium", "High", "Very High")), 
         Dalc = factor(Dalc, 
                       levels=c(1,2,3,4,5), 
                       labels=c("Very Low", "Low", "Medium", "High", "Very High")),
         Walc = factor(Walc, 
                       levels=c(1,2,3,4,5), 
                       labels=c("Very Low", "Low", "Medium", "High", "Very High")),
         health = factor(health, 
                         levels=c(1,2,3,4,5), 
                         labels=c("Very Bad", "Bad", "Average", "Good", "Very Good")),
         Medu = factor(Medu, #convert education levels to factor levels
                       levels = c(0,1,2,3,4), 
                       labels = c("None","Primary","Middle","Secondary","Higher")),
         Fedu = factor(Fedu, 
                       levels = c(0,1,2,3,4), 
                       labels = c("None","Primary","Middle","Secondary","Higher"))
         )
```

Then, export the reformatted data into a .csv file:
```{r}
write_csv(student_por, "studalc-por.csv")
```
